### ISSUE TITLE
Filtering by dates

### ISSUE THREAD

**Issue by dmldavies** [WorldHealthOrganization/poliprep#19]
Great Job sir.

My issue is with the filter argument in the updated ona_get_data() function. It's unclear how to use it to filter by dates. I have tried the following: 

1. I thought to make the dates an object so I can always just change the figures. 

```
> date_filter <- list(
+   submission_time = list(
+     "$gte" = "2024-11-05T00:00:00",
+     "$lte" = "2024-11-12T14:30:00"
+   )
+ )
> 
> ona_eim_ipds_ih_epm <- poliprep::get_ona_data(
+   form_id = 7178,
+   api_token = Sys.getenv("ONA_TOKEN"),
+   filters = date_filter
+   )
```

2. I tried to use list() and _submission_time as parameters
```
> ona_eim_ipds_ih_epm_date_filter <- poliprep::get_ona_data(
+   form_id = 7178,
+   api_token = Sys.getenv("ONA_TOKEN"),
+   filters = list(_submission_time = c("2024-11-11"))
```

3. I was getting an error for using _submission_time. So I thought removing the underscore would work
```
> ona_eim_ipds_ih_epm_date_filter <- poliprep::get_ona_data(
+   form_id = 7178,
+   api_token = Sys.getenv("ONA_TOKEN"),
+   filters = list(submission_time = c("2024-11-11"))
+ )
```
4. Here I tried using the endtime column since it did not have the underscore prefix
```
> ona_eim_ipds_ih_epm_date_filter <- poliprep::get_ona_data(
+   form_id = 7178,
+   api_token = Sys.getenv("ONA_TOKEN"),
+   filters = list(endtime = c("2024-11-11"))
+ )
```

5. Same idea as bullet one but with endtime instead of submission_time
```
> date_filter <- list(
+   endtime = list(
+     "$gte" = "2024-11-05T00:00:00",
+     "$lte" = "2024-11-12T13:00:00"
+   )
+ )
> 
> ona_eim_ipds_ih_epm_date_filter <- poliprep::get_ona_data(
+   form_id = 7178,
+   api_token = Sys.getenv("ONA_TOKEN"),
+   filters = date_filter
+ )
```

Sadly none of these options generated any data.

Would be grateful if this could be fix of be clarified.

Regards.
Thank you

**Comment by truenomad** [comment]
Hi Davies,

Thank you for this request! I’ve managed to incorporate the additional filters using comparators, though it was a bit tricky given that the querying is done in MongoDB. I’ve worked to make this as straightforward as possible using R input.

To select specific elements in a column, you can now use logical_filters. For example, to select 'BORNO' and “KANO” in the `states` column, you can input `list(states = c("BORNO", "KANO"))`.

For filtering ranges, you can use comparison_filters, which always starts with a tilde (~) and then the conditions are written in a standard R syntax. For example:

```~ `today` >= "2023-02-04" & `today` <= "2025-02-04"```

This filter selects rows where the today column falls within the specified date range. By combining `logical_filters` and `comparison_filters`, we can create a versatile query for our dataset.

Here’s an example:

```
ona_eim_ipds_ih_epm <- get_ona_data(
  form_id = 7178,
  api_token = Sys.getenv("ONA_TOKEN"),
  selected_columns = c("states", "endtime", "today", "_duration"),
  logical_filters = list(states = c("BORNO", "KANO")),
  comparison_filters = (~ `today` >= "2023-02-04" & `today` <= "2025-02-04")
)
```

This example selects the columns `states`, `endtime`, `today`, and `_duration` from form ID 7178, and filters to include only rows where the states column is either “Borno” or “Kano,” and where the today column falls within the specified date range.

Before applying any of these filters, please double-check both the column names and their contents to ensure they match your intended filters. For example, if you plan to use the `submission_time` column, note that in form 7178, this column is labelled `_submission_time`.

Please play around with this and let me know if there are any issues.

**Comment by jasons-pro** [comment]
Dear colleagues,
Are we still exploring the possibility of moving all our scripts to GitHub as early planned? I think it has benefits. Thank you for your collaboration.
