### ISSUE TITLE
⭐ A function that automatically detects the format of the date column 

### ISSUE THREAD

**Issue by truenomad** [WorldHealthOrganization/poliprep#7]
So reviewing `prep_match_datatypes` made me realise it may be worthwhile creating a function that automatically detects the format of a given date string. It'll be a big help for data cleaning and preprocessing tasks where different datasets will have many different date formats.

Can use the `anytime` package to source all the potential date formats available using the `getFormats()`. 

One major challenge with this function is the ambiguity in date formats. For example, some formats are inherently ambiguous (e.g., 01-04-2021 could mean January 4th or April 1st), making it difficult to determine the correct format without additional context.

I think we can be more easily resolve this in columns with many dates, but it becomes more challenging when working with smaller samples, such as individual vectors.

The usage would look something like this: `get_date_format("2023-02-26")` and would then give us `"%Y-%m-%d"`

**Comment by DemevengDerrick** [comment]
I copletely agree with you as I was trying to identify all possible date format to factor them in the code.

**Comment by truenomad** [comment]
So I have noticed that lubridate has `parse_date_time` function, which may be of use to us. It has additional functionalities, like training on a subset of formats as input vectors before parsing. Could try this with `prep_match_datatypes` ensure that all dates in the ref data are in the same format, but would still need to find a way to map the date format in the ref data to that of the target data.

```
my_dates <- 
  c("01.02.2021", "1988-02-03", "1996/12/03", 
    "19/02/2021", "1988-15-03", "05-12-2023", "5-27-2022")

lubridate::parse_date_time(
  my_dates,  
  orders = c("dmy","mdy", "ymd", 'ydm'), train = TRUE)

[1] "2021-02-01 UTC" "1988-03-02 UTC" "1996-12-03 UTC" "2021-02-19 UTC" 
[2] "1988-03-15 UTC" "2023-05-12 UTC" "2022-05-27 UTC"
```

**Comment by DemevengDerrick** [comment]
Great!! Also found that as.POSIXlt and as.POSIXct have a tryFormat option as below. I am trying to play around.
```
as.POSIXlt(x, tz = "", format,
           tryFormats = c("%Y-%m-%d %H:%M:%OS",
                          "%Y/%m/%d %H:%M:%OS",
                          "%Y-%m-%d %H:%M",
                          "%Y/%m/%d %H:%M",
                          "%Y-%m-%d",
                          "%Y/%m/%d"),
           optional = FALSE, …)
```

**Comment by truenomad** [comment]
> Great!! Also found that as.POSIXlt and as.POSIXct have a tryFormat option as below. I am trying to play around.
> 
> ```
> 
> as.POSIXlt(x, tz = "", format,
> 
>            tryFormats = c("%Y-%m-%d %H:%M:%OS",
> 
>                           "%Y/%m/%d %H:%M:%OS",
> 
>                           "%Y-%m-%d %H:%M",
> 
>                           "%Y/%m/%d %H:%M",
> 
>                           "%Y-%m-%d",
> 
>                           "%Y/%m/%d"),
> 
>            optional = FALSE, …)
> 
> ```

Wonderful! This is a great find. 

Looking forward to see how you use it.
